{{- if .Values.policies.enforceApprovedRegistries.enabled }}
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: eksallowedimageseffect
  annotations:
    description: "{{ .Values.policies.enforceApprovedRegistries.annotations.description }}"
    standard: "{{ .Values.policies.enforceApprovedRegistries.annotations.standard }}"
    shortName: "{{ .Values.policies.enforceApprovedRegistries.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  crd:
    spec:
      names:
        kind: EksAllowedImagesEffect
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package eksallowedimageseffect

        violation[{"msg": msg}] {
          image := input.review.object.spec.containers[_].image
          approved_registries := {{ toJson .Values.policies.enforceApprovedRegistries.parameters.allowedRegistries }}
          not startswith(image, approved_registries[_])
          msg := sprintf("Container image '%s' is not from an approved registry.", [image])
        }

---

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksAllowedImagesEffect
metadata:
  name: enforce-approved-registries
  annotations:
    description: "{{ .Values.policies.enforceApprovedRegistries.annotations.description }}"
    standard: "{{ .Values.policies.enforceApprovedRegistries.annotations.standard }}"
    shortName: "{{ .Values.policies.enforceApprovedRegistries.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  enforcementAction: deny
  match:
    excludedNamespaces:
      - kube-system
      - amazon-cloudwatch
      - gatekeeper-system
      - amazon-guardduty
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedRegistries: {{ .Values.policies.enforceApprovedRegistries.parameters.allowedRegistries | toJson }}
{{- end }}
