{{- if .Values.policies.enforceNonRootUser.enabled }}
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: eksenforcenonrootuser
  annotations:
    description: "{{ .Values.policies.enforceNonRootUser.annotations.description }}"
    standard: "{{ .Values.policies.enforceNonRootUser.annotations.standard }}"
    shortName: "{{ .Values.policies.enforceNonRootUser.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  crd:
    spec:
      names:
        kind: EksEnforceNonRootUser
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package eksenforcenonrootuser

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          sc := container.securityContext
          not sc.runAsNonRoot == true
          msg := sprintf("Container '%s' in Pod '%s' is not set to run as non-root.", [container.name, input.review.object.metadata.name])
        }

---

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksEnforceNonRootUser
metadata:
  name: enforce-non-root-user
  annotations:
    description: "{{ .Values.policies.enforceNonRootUser.annotations.description }}"
    standard: "{{ .Values.policies.enforceNonRootUser.annotations.standard }}"
    shortName: "{{ .Values.policies.enforceNonRootUser.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  enforcementAction: {{ if eq .Values.infra_env "dev" }}"dryrun"{{ else }}"deny"{{ end }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
{{- end }}
