{{- if .Values.policies.restrictHostFilesystemAccess.enabled }}
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: ekspsphostfilesystem
  annotations:
    description: "{{ .Values.policies.restrictHostFilesystemAccess.annotations.description }}"
    standard: "{{ .Values.policies.restrictHostFilesystemAccess.annotations.standard }}"
    shortName: "{{ .Values.policies.restrictHostFilesystemAccess.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  crd:
    spec:
      names:
        kind: EksPspHostFilesystem
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package ekspsphostfilesystem

        violation[{"msg": msg}] {
          volume := input.review.object.spec.volumes[_]
          volume.hostPath
          msg := sprintf("Pod '%s' uses hostPath volume '%s'.", [input.review.object.metadata.name, volume.name])
        }

---

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksPspHostFilesystem
metadata:
  name: restrict-host-filesystem-access
  annotations:
    description: "{{ .Values.policies.restrictHostFilesystemAccess.annotations.description }}"
    standard: "{{ .Values.policies.restrictHostFilesystemAccess.annotations.standard }}"
    shortName: "{{ .Values.policies.restrictHostFilesystemAccess.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  enforcementAction: {{ if eq .Values.infra_env "dev" }}"dryrun"{{ else }}"deny"{{ end }}
  match:
    excludedNamespaces:
      - kube-system
      - amazon-cloudwatch
      - gatekeeper-system
      - amazon-guardduty
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
{{- end }}
