{{- if .Values.policies.enforceSecretMounting.enabled }}
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: eksmountedsecrets
  annotations:
    description: "{{ .Values.policies.enforceSecretMounting.annotations.description }}"
    standard: "{{ .Values.policies.enforceSecretMounting.annotations.standard }}"
    shortName: "{{ .Values.policies.enforceSecretMounting.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  crd:
    spec:
      names:
        kind: EksMountedSecrets
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package eksmountedsecrets

        violation[{"msg": msg}] {
          volume := input.review.object.spec.volumes[_]
          volume.secret
          not volume.secret.defaultMode == 420  # 420 octal is 0644 in decimal
          msg := sprintf("Volume '%s' in Pod '%s' does not have secret mounted as read-only.", [volume.name, input.review.object.metadata.name])
        }

---

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksMountedSecrets
metadata:
  name: enforce-secret-mounting
  annotations:
    description: "{{ .Values.policies.enforceSecretMounting.annotations.description }}"
    standard: "{{ .Values.policies.enforceSecretMounting.annotations.standard }}"
    shortName: "{{ .Values.policies.enforceSecretMounting.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  enforcementAction: {{ if eq .Values.infra_env "dev" }}"dryrun"{{ else }}"deny"{{ end }}
  match:
    excludedNamespaces:
      - kube-system
      - amazon-cloudwatch
      - gatekeeper-system
      - amazon-guardduty
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
{{- end }}
