{{- if .Values.policies.enforceResourceLimits.enabled }}
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: eksresourcelimits
  annotations:
    description: "{{ .Values.policies.enforceResourceLimits.annotations.description }}"
    standard: "{{ .Values.policies.enforceResourceLimits.annotations.standard }}"
    shortName: "{{ .Values.policies.enforceResourceLimits.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  crd:
    spec:
      names:
        kind: EksResourceLimits
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package eksresourcelimits

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          not has_resource_limits(container)
          msg := sprintf("Container '%s' in Pod '%s' does not have resource limits set.", [container.name, input.review.object.metadata.name])
        }

        has_resource_limits(container) {
          container.resources.limits.cpu
          container.resources.limits.memory
        }

---

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksResourceLimits
metadata:
  name: enforce-resource-limits
  annotations:
    description: "{{ .Values.policies.enforceResourceLimits.annotations.description }}"
    standard: "{{ .Values.policies.enforceResourceLimits.annotations.standard }}"
    shortName: "{{ .Values.policies.enforceResourceLimits.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  enforcementAction: {{ if eq .Values.infra_env "dev" }}"dryrun"{{ else }}"deny"{{ end }}
  match:
    excludedNamespaces:
      - kube-system
      - amazon-cloudwatch
      - gatekeeper-system
      - amazon-guardduty
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
{{- end }}
