{{- if .Values.policies.restrictClusterAdminBinding.enabled }}
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: eksrestrictclusteradmin
  annotations:
    description: "{{ .Values.policies.restrictClusterAdminBinding.annotations.description }}"
    standard: "{{ .Values.policies.restrictClusterAdminBinding.annotations.standard }}"
    shortName: "{{ .Values.policies.restrictClusterAdminBinding.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  crd:
    spec:
      names:
        kind: EksRestrictClusterAdmin
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package restrict_cluster_admin_binding

        violation[{"msg": msg}] {
          input.review.kind.kind == "RoleBinding" or input.review.kind.kind == "ClusterRoleBinding"

          binding := input.review.object
          resource_name := binding.metadata.name

          # Exclude specific bindings
          not is_excluded_binding(resource_name)

          binding.roleRef.kind == "ClusterRole"
          binding.roleRef.name == "cluster-admin"

          msg := sprintf("Binding '%s' should not use the cluster-admin role.", [resource_name])
        }

        # Function to determine if a binding should be excluded
        is_excluded_binding(name) {
          name_in_excluded_names(name) or name_matches_excluded_patterns(name)
        }

        name_in_excluded_names(name) {
          excluded_names := ["admin", "system:aggregate-to-edit", "system:controller:clusterrole-aggregation-controller", "eks:addon-manager", "gatekeeper-manager-role"]
          name == excluded_names[_]
        }

        name_matches_excluded_patterns(name) {
          excluded_patterns := ["^system:.*", "^eks.*"]
          pattern := excluded_patterns[_]
          regex.match(pattern, name)
        }


---

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksRestrictClusterAdmin
metadata:
  name: restrict-cluster-admin-binding
  annotations:
    description: "{{ .Values.policies.restrictClusterAdminBinding.annotations.description }}"
    standard: "{{ .Values.policies.restrictClusterAdminBinding.annotations.standard }}"
    shortName: "{{ .Values.policies.restrictClusterAdminBinding.annotations.shortName }}"
    app_id: "{{ .Values.global.annotations.app_id }}"
    risk_type: "{{ .Values.global.annotations.risk_type }}"
    risk_classification: "{{ .Values.global.annotations.risk_classification }}"
    snow_id: "{{ .Values.global.annotations.snow_id }}"
    exception_register: "{{ .Values.global.annotations.exception_register }}"
    exception_id: "{{ .Values.global.annotations.exception_id }}"
    exemption_reason: "{{ .Values.global.annotations.exemption_reason }}"
    exemption_tenant: "{{ .Values.global.annotations.exemption_tenant }}"
    exemption_infra_env: "{{ .Values.global.annotations.exemption_infra_env }}"
spec:
  enforcementAction: {{ if eq .Values.infra_env "dev" }}"dryrun"{{ else }}"deny"{{ end }}
  match:
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["ClusterRoleBinding"]
  parameters:
    allowedSubjects: {{ .Values.policies.restrictClusterAdminBinding.parameters.allowedSubjects | toJson }}
{{- end }}
