apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: preventrbacwildcards
spec:
  crd:
    spec:
      names:
        kind: PreventRbacWildcards
      validation:
        openAPIV3Schema:
          properties:
            excludedRoles:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package preventrbacwildcards

        violation[{"msg": msg}] {
          input.review.kind.kind == "ClusterRole" or input.review.kind.kind == "Role"

          role := input.review.object
          resource_name := role.metadata.name

          # Exclude specific roles
          not is_excluded_role(resource_name)

          # Check for wildcards in resources, verbs, or apiGroups
          rule := role.rules[_]

          rule.resources[_] == "*" or
          rule.verbs[_] == "*" or
          rule.apiGroups[_] == "*"

          msg := sprintf("Role '%s' should not contain wildcards in resources, verbs, or apiGroups.", [resource_name])
        }

        is_excluded_role(name) {
          excluded_roles := input.parameters.excludedRoles
          some excluded
          excluded := excluded_roles[_]
          name_matches_pattern(name, excluded)
        }

        name_matches_pattern(name, pattern) {
          contains(pattern, "*")
          regex_pattern := glob.match(pattern, [], name)
        } else {
          name == pattern
        }
