apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksAllowedCapabilitiesEffect
metadata:
  name: enforce-allowed-capabilities
spec:
  enforcementAction: dryrun
  parameters:
    allowedCapabilities:
      - "NET_BIND_SERVICE"
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
