apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksBlockPrivilegeEscalation
metadata:
  name: prevent-privilege-escalation
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
