apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksContainersProbeEffect
metadata:
  name: enforce-container-probes
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
