apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictSecretAccess
metadata:
  name: restrict-secret-access
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["Role", "ClusterRole"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
  parameters:
    excludedRoles:
      - "admin"
      - "system:aggregate-to-edit"
      - "system:controller:clusterrole-aggregation-controller"
      - "eks:addon-manager"
      - "gatekeeper-manager-role"
      - "system:*"
      - "eks:*"
