apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksEnforceSecretAccess
metadata:
  name: restrict-secret-access
spec:
  enforcementAction: dryrun
  parameters:
    allowedRoles:
      - "allowed-secret-reader"
  match:
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["Role", "ClusterRole"]
