apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksMountedSecrets
metadata:
  name: enforce-secret-mounting
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
