apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksNoAutomountServiceAccountToken
metadata:
  name: enforce-automount-sa-token
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
