apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksNetPolEnforce
metadata:
  name: enforce-network-policies
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
