apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksNoWildcards
metadata:
  name: prevent-rbac-wildcards
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["Role", "ClusterRole"]
