apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksPrivEscalationEffect
metadata:
  name: prevent-privileged-containers
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
