apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksPSPHostNamespace
metadata:
  name: restrict-host-namespaces
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
