apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksPSPHostFilesystem
metadata:
  name: restrict-host-filesystem-access
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
