apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictClusterAdminBinding
metadata:
  name: restrict-cluster-admin-binding
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["RoleBinding", "ClusterRoleBinding"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
  parameters:
    excludedBindings:
      - "admin"
      - "system:aggregate-to-edit"
      - "system:controller:clusterrole-aggregation-controller"
      - "eks:addon-manager"
      - "gatekeeper-manager-role"
      - "system:*"
      - "eks:*"
