apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksRestrictDefaultServiceAccount
metadata:
  name: prevent-default-service-account-use
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
