apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksReadOnlyRootFilesystem
metadata:
  name: enforce-readonly-root-filesystem
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
