apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksResourceLimits
metadata:
  name: enforce-resource-limits
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
