apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksSetSecurityContext
metadata:
  name: enforce-security-context
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
